### ISSUE TITLE
The defaul protocol for the cluster URL is not defined

### ISSUE THREAD

**Issue by hguerrero** [kcctl/kcctl#142]
When creating a context with 

`kcctl config set-context --cluster localhost:8083 local`

If you type `kcctl info` you get an error message:

```
java.lang.IllegalArgumentException: protocol = localhost host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:186)
	at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.selectHttpProxy(QuarkusRestClientBuilder.java:385)
	at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:282)
	at org.kcctl.command.InfoCommand.run(InfoCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:125)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

Looks like you need to define like this to make it work:

`kcctl config set-context --cluster http://localhost:8083 local`

Expected: 

kcctl will use HTTP as default protocol if non provided.

**Comment by gunnarmorling** [comment]
I'm leaning towards requiring the protocol; it could be HTTPS after all. Gonna close this as won't fix in this light.
