### ISSUE TITLE
kcctl doesnt work with JDK 1.8

### ISSUE THREAD

**Issue by sfc-gh-japatel** [kcctl/kcctl#168]
Hello, 
I tried using JDK 1.8 
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/runner/QuarkusEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
It works fine with JDK 11. I guess because io/quarkus/bootstrap/runner/QuarkusEntryPoint requires JDK 11?

Is there another workaround?

Thank you!

**Comment by gunnarmorling** [comment]
That's intentional, we don't aim for compatibility with Java 1.8. Given that the expected way of consuming kcctl is via the (self-contained) native binaries, we actually require Java 17 for building kcctl and it's also the classfile format version produced when building kcctl as a non-native JAR. Any reason for not using the native binaries? The experience is much better due to the much faster starting time.

**Comment by sfc-gh-japatel** [comment]
That makes sense @gunnarmorling thanks! I added this in my zsh profile
```
alias kcctl='java -jar /Users/japatel/Desktop/Kafka-Connector/kcctl/target/quarkus-app/quarkus-run.jar'
```

I suppose I can just use the binary instead of using the built jar.

**Comment by sfc-gh-japatel** [comment]
I will close this out, I fixed it by removing the alias. I did run brew install before that but it was somehow overridden by alias. Thank you!
