### ISSUE TITLE
Unable to connect to Kafka connect with self signed certificate

### ISSUE THREAD

**Issue by arijitmazumdar** [kcctl/kcctl#180]
Our kafka connect running with self signed certificate. While trying to Kafka connect getting following error. Where and how to add certificate to kcctl? I guess it will not solve if we add the certs in jvm.

```
kcctl get plugins                                                    
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path
 building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to 
requested target
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpCl
ient43Engine.java:321)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:494)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at jdk.proxy4.$Proxy219.getConnectorPlugins(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at jdk.proxy4.$Proxy220.getConnectorPlugins(Unknown Source)
        at org.kcctl.command.GetPluginsCommand.run(GetPluginsCommand.java:47)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
```

**Comment by arijitmazumdar** [comment]
With a little bit of study on GraalVM was able to solve the issue. Refer - https://www.graalvm.org/22.1/reference-manual/native-image/CertificateManagement/#run-time-options. The command looks a little ugly but works fine.

```
kcctl -Djavax.net.ssl.trustStore=/home/arijit_mazumdar_external_gcp_tel/truststore.p12 \
-Djavax.net.ssl.trustStorePassword=mystorepassword \
-Djavax.net.ssl.trustStoreProvider=SUN \
get connectors
```
