### ISSUE TITLE
kcctl describe plugin io.debezium.connector.mysql.MySqlConnector fails with exception

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#266]
Getting this exception when running `kcctl describe plugin io.debezium.connector.mysql.MySqlConnector`.

```
org.kcctl.service.KafkaConnectException: Invalid value com.mysql.cj.jdbc.Driver for configuration database.jdbc.driver: Class com.mysql.cj.jdbc.Driver could not be found.
	at org.kcctl.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:32)
	at org.kcctl.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:23)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:155)
	at jdk.proxy4.$Proxy61.getConnectorPluginConfig(Unknown Source)
	at org.kcctl.command.DescribePluginCommand.call(DescribePluginCommand.java:74)
	at org.kcctl.command.DescribePluginCommand.call(DescribePluginCommand.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

More an issue on the Connect side itself than anything else, but still worth exploring and hopefully fixing.

**Comment by mimaison** [comment]
Yeah I noticed this issue with most of the Debezium connectors. IIRC only Mongo worked.

**Comment by gunnarmorling** [comment]
@mimaison just running into this again. Do you have any idea what's the issue here? Those classes definitely exist, wondering whether something is broken with classloading in Connect here.

**Comment by gunnarmorling** [comment]
Pinging @C0urante, too; does this ring a bell for you: calls like

```
http localhost:8083/connector-plugins/io.debezium.connector.sqlserver.SqlServerConnector/config
```

fail due to class-loading issues:

```
distributed-caching-connect-1               | 2023-01-21 11:50:33,274 ERROR  ||  Uncaught exception in REST call to /connector-plugins/io.debezium.connector.sqlserver.SqlServerConnector/config   [org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper]
distributed-caching-connect-1               | org.apache.kafka.common.config.ConfigException: Invalid value io.debezium.storage.kafka.history.KafkaSchemaHistory for configuration schema.history.internal: Class io.debezium.storage.kafka.history.KafkaSchemaHistory could not be found.
distributed-caching-connect-1               | 	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
distributed-caching-connect-1               | 	at org.apache.kafka.common.config.ConfigDef$ConfigKey.<init>(ConfigDef.java:1172)
distributed-caching-connect-1               | 	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:152)
distributed-caching-connect-1               | 	at io.debezium.config.Field.group(Field.java:453)
distributed-caching-connect-1               | 	at io.debezium.config.ConfigDefinition.addToConfigDef(ConfigDefinition.java:104)
distributed-caching-connect-1               | 	at io.debezium.config.ConfigDefinition.configDef(ConfigDefinition.java:71)
distributed-caching-connect-1               | 	at io.debezium.connector.sqlserver.SqlServerConnectorConfig.configDef(SqlServerConnectorConfig.java:325)
distributed-caching-connect-1               | 	at io.debezium.connector.sqlserver.SqlServerConnector.config(SqlServerConnector.java:107)
distributed-caching-connect-1               | 	at org.apache.kafka.connect.runtime.AbstractHerder.connectorPluginConfig(AbstractHerder.java:799)
distributed-caching-connect-1               | 	at org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource.getConnectorConfigDef(ConnectorPluginsResource.java:166)
```

That class `KafkaSchemaHistory` definitely exists though and the connector can be instantiated just fine. So far I've observed that all these cases referred to classes in _another_ JAR though (e.g. database driver, DBZ core JAR, etc.), rather than the JAR with the connector class itself (but as said, those JARs are part of the same plug-in directory and are found when instantiating the connector).

**Comment by C0urante** [comment]
Ah yep, looks like an upstream bug in Connect. Filed https://issues.apache.org/jira/browse/KAFKA-14645 to track, should have a PR out for it within the hour.

**Comment by C0urante** [comment]
@gunnarmorling @mimaison since it's caused by an upstream bug, should we close this ticket?

**Comment by gunnarmorling** [comment]
Thanks for logging that upstream issue. Will close this one here in this light. Would that fix be part of the next 3.3.x AK release?
