### ISSUE TITLE
Update brew to latest version Beta1

### ISSUE THREAD

**Issue by hguerrero** [kcctl/kcctl#311]
Currently, the version available in brew is `kcctl 1.0.0.Alpha5` while the latest release available is `Beta1`

**Comment by gunnarmorling** [comment]
Mh, that's interesting. @aalmiray, does this ring a bell, could we some not have pushed that release to Brew?

**Comment by aalmiray** [comment]
The release logs show the following:

```
[INFO]  Publishing distributions
[INFO]    - Publishing kcctl distribution
[DEBUG]     [appimage] skipping for kcctl distribution
[DEBUG]     [asdf] skipping for kcctl distribution
[INFO]      [brew] publishing kcctl distribution
[DEBUG]     [brew] creating props for kcctl/brew
[DEBUG]     [brew] filling distribution properties into props
[DEBUG]     [brew] filling git properties into props
[DEBUG]     [brew] filling artifact properties into props
[DEBUG]     [brew] filling packager properties into props
[INFO]      [brew] setting up repository kcctl/homebrew-tap
[DEBUG]     [brew] locating repository kcctl/homebrew-tap
[DEBUG]     [brew] lookup repository kcctl/homebrew-tap
[DEBUG]     [brew] lookup repository kcctl/homebrew-tap
[WARN]      [brew] failure: Unexpected error updating kcctl/homebrew-tap
org.jreleaser.model.spi.packagers.PackagerProcessingException: Unexpected error updating kcctl/homebrew-tap
	at org.jreleaser.packagers.AbstractRepositoryPackagerProcessor.doPublishDistribution(AbstractRepositoryPackagerProcessor.java:138)
	at org.jreleaser.packagers.AbstractPackagerProcessor.publishDistribution(AbstractPackagerProcessor.java:182)
	at org.jreleaser.packagers.BrewPackagerProcessor.publishDistribution(BrewPackagerProcessor.java:74)
	at org.jreleaser.engine.distribution.DistributionProcessor.publishDistribution(DistributionProcessor.java:141)
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:140)
	at org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:111)
	at org.jreleaser.engine.distribution.Distributions.process(Distributions.java:95)
	at org.jreleaser.workflow.PublishWorkflowItem.doInvoke(PublishWorkflowItem.java:37)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:102)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:148)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:483)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:407)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.read(GHRepository.java:130)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:624)
	at org.jreleaser.sdk.github.Github.findRepository(Github.java:122)
	at org.jreleaser.sdk.github.GithubReleaser.maybeCreateRepository(GithubReleaser.java:256)
	at org.jreleaser.packagers.AbstractRepositoryPackagerProcessor.doPublishDistribution(AbstractRepositoryPackagerProcessor.java:69)
	... 41 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/kcctl/homebrew-tap
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2061)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2056)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2055)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1612)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:174)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:314)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:92)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:76)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:449)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:399)
	... 48 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/kcctl/homebrew-tap
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2010)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	... 48 more
```

@gunnarmorling I think the secret GH token identified by `JRELEASER_HOMEBREW_GITHUB_TOKEN` is no longer valid. Wasn't this token created with a set expiration date?

**Comment by gunnarmorling** [comment]
Mh, yeah, indeed. How do I create a new one?

**Comment by gunnarmorling** [comment]
Weird though that the release job didn't fail due to that?

**Comment by aalmiray** [comment]
It didn't fail because the release configuration is resilient 

https://github.com/kcctl/kcctl/blob/d5e6c3db080147ade42c9ec6b375e2a22241100c/pom.xml#L485-L489

Line 487 has the secret sauce 😅

**Comment by aalmiray** [comment]
> Mh, yeah, indeed. How do I create a new one?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by gunnarmorling** [comment]
> It didn't fail because the release configuration is resilient

Is this a good thing though? I'd rather want it to fail, so as to know that something is wrong. Exactly to avoid a situation like this where a release silently didn't get pushed.

**Comment by gunnarmorling** [comment]
Re creating a new PAT, is there a description of of the permissions required by JReleaser somewhere?

**Comment by gunnarmorling** [comment]
More specifically, I'd like to use a new "[fine-grained access token](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/)". The JReleaser docs still describe the more coarse-grained "classic" tokens. So what does that token exactly need to allow, pushing commits to the homebrew-tap repo? Anything else? Happy to be your guinea pig for updating the JReleaser instructions, @aalmiray 🐷 .

**Comment by aalmiray** [comment]
> Is this a good thing though? I'd rather want it to fail, so as to know that something is wrong. Exactly to avoid a situation like this where a release silently didn't get pushed.

Right. Except that the way the release works we’ll have a tag and a git release but broken packagers. From this point rolling back is a manual step _or_ we burn the release number, fix the issue and try again with a new number. 

Let me know what you think and we make adjustments.

**Comment by aalmiray** [comment]
> More specifically, I'd like to use a new "[fine-grained access token](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/)". The JReleaser docs still describe the more coarse-grained "classic" tokens. So what does that token exactly need to allow, pushing commits to the homebrew-tap repo? Anything else? Happy to be your guinea pig 🐷 for updating the JReleaser instructions, @aalmiray.

I believe read/write repo access is enough. When I wrote the docs there were only classic tokens. I haven’t had a look at the new type of tokens so far thus I’ve no idea what changes may be required 😫

**Comment by gunnarmorling** [comment]
My preference would be burning the release number and move forward. It should happen rarely enough.

> I believe read/write repo access is enough.

Ok, cool. I'll set up a PAT with that tomorrow and trigger a release and let you know how it goes.

**Comment by aalmiray** [comment]
OK. While you’re at it feel free to update `pom.xml` by removing `continueOnError` from both brew and sdkman.

**Comment by gunnarmorling** [comment]
@aalmiray, actually, I tried right now, and [it failed](https://github.com/kcctl/kcctl/actions/runs/3976896403/jobs/6817700554) with this:

```
Error:  == JReleaser ==
Error:  org.jreleaser.model.JReleaserException: Version v1.0.0.Beta2 does not follow the semver spec
```

We have used v1.0.0.Beta2 before though? Or do I need to remove the "v" prefix and this is added automatically by JReleaser to the GH tag etc.?

**Comment by gunnarmorling** [comment]
Ok, so now it succeeded, using "1.0.0.Beta2". No update to the tap repo though 🤔 ?!

**Comment by aalmiray** [comment]
Huh, this is odd. I can see a fee things that can be improved:
- cache maven repo as dependencies are still downloaded
- invoke maven with -ntp to reduce noise
- brew package appears to be disabled. It might have something to do with the version. Will look in the logs

**Comment by aalmiray** [comment]
Looked further into the logs. JReleaser `1.4.0` finds the `brew` configuration defined at the packagers section as witnessed by

```
    brew:
        enabled: true
        active: release
        continueOnError: true
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        multiPlatform: true
        tap:
            enabled: true
            active: release
            owner: kcctl
            name: homebrew-tap
            tagName: v{{projectVersion}}
            branch: HEAD
            username: kcctl
            token: ************
        cask:
            enabled: false
```

However, it fails to enable, the `brew` configuration inside the `distributions` section (which is the one that will be used during publication). We only get

```
        brew:
            enabled: false
            active: never
            continueOnError: false
            commitAuthor:
            multiPlatform: false
            tap:
                enabled: false
                name: homebrew-tap
                token: **unset**
            cask:
                enabled: false
```

What's really odd is that I can see the `brew` configuration properly evaluated in both sections when running `jreleaser:config`. There might a bug in JReleaser indeed. I've prepared a PR with fixes as there's a workaround to get `1.4.0` working. The other option is to downgrade to `1.3.1` (I've tested both options).

**Comment by aalmiray** [comment]
Tja. I need a new GH token to create a branch in this repo 😭

**Comment by gunnarmorling** [comment]
Alrighty, ran another release, and all looking good now:

```
brew info kcctl/tap/kcctl
==> kcctl/tap/kcctl: stable 1.0.0.Beta3
```

@aalmiray, thanks you so much!
