### ISSUE TITLE
NullPointerException when invoking `kcctl patch offsets` without payload

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#422]
This situation should be handled more gracefully, i.e. by displaying an error message to the user rather than stacktrace:

```
kcctl patch offsets inventory-connector
java.lang.NullPointerException
	at org.kcctl.command.PatchOffsetsCommand.call(PatchOffsetsCommand.java:162)
	at org.kcctl.command.PatchOffsetsCommand.call(PatchOffsetsCommand.java:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by gunnarmorling** [comment]
CC @C0urante.

**Comment by C0urante** [comment]
I spent so much time figuring out how to get the mutually-exclusive source/sink offset argument types to work that I forgot to test out the most basic case 😂

**Comment by gunnarmorling** [comment]
> I spent so much time figuring out how to get the mutually-exclusive source/sink offset argument types to work that I forgot to test out the most basic case 😂

Haha, thanks for the quick fix!
