### ISSUE TITLE
In MAC kcctl binary is not working 

### ISSUE THREAD

**Issue by gcpcloudreddy** [kcctl/kcctl#65]
./kcctl info
javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/html;charset=utf-8 and type class dev.morling.kccli.service.KafkaConnectInfo

After setting the context am getting above error.

**Comment by gunnarmorling** [comment]
Can you actually reach Kafka Connect from the machine where you're running kcctl? There should be no need for increasing any time-outs really, any requests should be fast and short-lived.

**Comment by gcpcloudreddy** [comment]
Thanks for the reply

With INS environment , I can see get connectors working fine
But describe connector <connector name> giving below error
javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type */* and type class dev.morling.kccli.service.ErrorResponse
	at org.jboss.resteasy.core.interception.jaxrs.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:47)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:133)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:75)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:262)
	at dev.morling.kccli.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:26)
	at dev.morling.kccli.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:22)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
	at com.sun.proxy.$Proxy219.getConnectorTopics(Unknown Source)
	at dev.morling.kccli.command.DescribeConnectorCommand.call(DescribeConnectorCommand.java:81)
	at dev.morling.kccli.command.DescribeConnectorCommand.call(DescribeConnectorCommand.java:49)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:39)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

**Comment by gcpcloudreddy** [comment]
From Kafka, I received below logs

[2021-08-31 13:43:59,973] ERROR Uncaught exception in REST call to /connectors/<name>/topics (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:250)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)

**Comment by gunnarmorling** [comment]
Which version of Kafka Connect are you running? Something old by any chance?

**Comment by gcpcloudreddy** [comment]
I use below version
kafka_2.12-2.4.0.tgz
"version":"2.4.0",

**Comment by gunnarmorling** [comment]
Ok, thanks, I can reproduce this now. The topics endpoint doesn't exist in Kafka Connect 2.4 yet. So we should make sure to only query it if it actually supported by the backend version in question. @SiddiqueAhmad, @karim-elngr, perhaps something interesting for one of you to pick up, if you're still interested?

**Comment by SiddiqueAhmad** [comment]
I am interested just taking up new job so kind of occupancy. I will do it asap.

**Comment by gunnarmorling** [comment]
Congrats on the new job, @SiddiqueAhmad! And no worries, I thought I'd ping you just in case.

**Comment by gcpcloudreddy** [comment]
Hi @gunnarmorling 

just wanted to know If above issue fixed ....

**Comment by gunnarmorling** [comment]
Hey, nope, no news here yet. Perhaps you'd be interested in sending a PR
with the fix yourself? It's a fairly easy fix, great to get started diving
into the code base :)

>

**Comment by gcpcloudreddy** [comment]
Oh i see, Haa sorry to say am not at all coding guy so far... 
I just work on Infra side tools like ansible , jenkins

**Comment by SiddiqueAhmad** [comment]
@gunnarmorling  thanks for your wishes, and today I got time so sent the pull request, please review and comment

**Comment by gunnarmorling** [comment]
Applied. Thx a lot, @SiddiqueAhmad!

**Comment by gcpcloudreddy** [comment]
Thank you @SiddiqueAhmad  @gunnarmorling , let me test all use-cases again , Have a good day

**Comment by gcpcloudreddy** [comment]
$ kcctl get connectors
javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/html and type class dev.morling.kccli.service.ErrorResponse
	at org.jboss.resteasy.core.interception.jaxrs.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:47)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:133)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:75)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:262)
	at dev.morling.kccli.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:26)
	at dev.morling.kccli.service.KafkaConnectResponseExceptionMapper.toThrowable(KafkaConnectResponseExceptionMapper.java:22)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
	at com.sun.proxy.$Proxy219.getConnectorStatus(Unknown Source)
	at dev.morling.kccli.command.GetConnectorsCommand.run(GetConnectorsCommand.java:55)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:39)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

**Comment by gcpcloudreddy** [comment]
Am seeing above error for get connectors, describe works fine
